# Generated by Django 4.0.2 on 2022-02-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zmk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Zmk',
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=120)),
                ('weight', models.FloatField()),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('receiving_date', models.DateField(blank=True, null=True)),
                ('zmk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rts', to='import_data.zmk')),
            ],
            options={
                'verbose_name_plural': 'RTS',
            },
        ),
    ]
