# Generated by Django 4.0.2 on 2022-02-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
