# Generated by Django 4.0.2 on 2022-02-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='zmk',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='zmk',
        ),
    ]
