# Generated by Django 4.0.2 on 2022-02-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0002_registry_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zmk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='registry',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registry',
            name='num',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registry',
            name='receiving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
