# Generated by Django 4.0.2 on 2022-02-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0003_zmk_registry_departure_date_registry_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='zmk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rts', to='import_data.zmk'),
        ),
    ]
