# Generated by Django 4.0.2 on 2022-02-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0004_registry_zmk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name_plural': 'RTS'},
        ),
        migrations.AlterModelOptions(
            name='zmk',
            options={'verbose_name_plural': 'Zmk'},
        ),
    ]
